apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-application
  labels:
    name: employee-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: employee-application
  template:
    metadata:
      labels:
        name: employee-application
    spec:
      containers:
      - name: employee-application
        image: cybnamespace/cybage-alm-ems-stg:tagname
        ports:
        - containerPort: 8080
